name: Run Full E2E Tests

on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java for Serenity
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up Node.js for frontend and backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      # Install and run backend
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend
        working-directory: backend
        run: npm run dev &

      # Install and run frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Start frontend
        working-directory: frontend
        run: npm run dev &

      # Run Serenity BDD E2E tests
      - name: Run Serenity tests
        working-directory: test
        run: mvn clean verify
        
      # Optional: Upload Serenity Report
      - name: Upload Serenity Report
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: test/target/site/serenity
